export const SET_MODAL_LOGIN = 'SET_MODAL_LOGIN';
export const REMOVE_MODAL_LOGIN = 'REMOVE_MODAL_LOGIN';
export const SET_MODAL_REGISTER = 'SET_MODAL_REGISTER';
export const REMOVE_MODAL_REGISTER = 'REMOVE_MODAL_REGISTER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
